### ISSUE TITLE
Having error

### ISSUE THREAD

**Issue by tachsin** [HellAmbro/Trading212API#28]
Running the example I get the following error:

```[01:17:48] Starting PyTrading212 in LIVE Mode                                                                                                                console.py:12
[01:17:50] Authenticating                                                                                                                                    console.py:12
Traceback (most recent call last):
  File "C:\Users\tachs\Desktop\trading212\trading212_v2.py", line 9, in <module>
    equity = Equity(email='xxxxxx@gmail.com', password='xxxxxx',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tachs\Desktop\trading212\Lib\site-packages\pytrading212\trading212.py", line 239, in __init__
    super().__init__(email, password, driver, mode, constants.Trading.EQUITY)
  File "C:\Users\tachs\Desktop\trading212\Lib\site-packages\pytrading212\trading212.py", line 50, in __init__
    self.driver.find_element(By.NAME, "email").send_keys(email)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tachs\Desktop\trading212\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 831, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tachs\Desktop\trading212\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\tachs\Desktop\trading212\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="email"]"}
  (Session info: chrome=111.0.5563.147)

**Comment by tachsin** [comment]
the problem persists, I tried maximizing the driver with `driver.maximize_window()`, no change

**Comment by HellAmbro** [comment]
Hi, thanks for reporting, can you please share your code, I've tried to reproduce the error but it's working for me

**Comment by HellAmbro** [comment]
This error can be related to internet connection and slow speed of T212 to load i think.
Please follow these steps and let me know so i can update the core accordingly.

1. clone this repository
2. create a fresh and clean virtual environment
3. add this line `WebDriverWait(self.driver, 120).until(expected_conditions.visibility_of_element_located((By.NAME, "email")))`
  just below `console.log("Authenticating")` inside `trading212.py`
You should have something like that 
```
console.log("Authenticating")
WebDriverWait(self.driver, 120).until(expected_conditions.visibility_of_element_located((By.NAME, "email")))

# Authenticate
self.driver.find_element(By.NAME, "email").send_keys(email)
self.driver.find_element(By.NAME, "password").send_keys(password)
```

Please let me know, if you need more help you can also join inside Discord group or contact me by email or other ways.
I'm not able to reproduce the error since it never happens to me.
